test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# amazon_dev:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.aws[:AKIAX2GSWHWQZKVMLY53] %>
#   secret_access_key: <%= Rails.application.credentials.aws[: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] %>
#   region: <%= Rails.application.credentials.aws[:us-west-1] %>
#   bucket: <%= Rails.application.credentials.aws[:dev][:taskrubyt-dev] %>

# amazon_prod:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.aws[:AKIAX2GSWHWQZKVMLY53] %>
#   secret_access_key: <%= Rails.application.credentials.aws[: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] %>
#   region: <%= Rails.application.credentials.aws[:us-west-1] %>
#   bucket: <%= Rails.application.credentials.aws[:prod][:taskrubyt-pro] %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
